# Generated by Django 4.1.2 on 2023-03-07 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.cargo')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo_interno', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('disponibles', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('estado_libro', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=50)),
                ('paginas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)])),
                ('imagen', models.ImageField(upload_to='media/booksImages/')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo.carrera')),
            ],
            options={
                'ordering': ['codigo_interno'],
            },
        ),
        migrations.CreateModel(
            name='Det_Prestamo',
            fields=[
                ('id_det_prestamo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant_libros', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('estatus', models.CharField(max_length=50)),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.prestamo')),
            ],
        ),
    ]
