# Generated by Django 4.1.2 on 2023-03-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(),
        ),
    ]
