# Generated by Django 4.1.2 on 2023-03-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0002_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
