# Generated by Django 4.1.2 on 2023-03-08 01:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0004_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='det_prestamo',
            name='libros',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=3), null=True, size=3),
        ),
    ]
