# Generated by Django 4.1.2 on 2023-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0005_det_prestamo_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_prestamo',
            name='libros',
        ),
        migrations.AddField(
            model_name='det_prestamo',
            name='libros',
            field=models.ManyToManyField(to='Modulo.libro'),
        ),
    ]
