# Generated by Django 4.1.2 on 2023-03-10 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0006_remove_det_prestamo_libros_det_prestamo_libros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Det_Librero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.librero')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.libro')),
            ],
        ),
    ]
