# Generated by Django 4.1.2 on 2023-03-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0008_remove_librero_id_usuario_delete_det_librero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_prestamo',
            name='libros',
        ),
        migrations.AddField(
            model_name='det_prestamo',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo.libro'),
        ),
    ]
