# Generated by Django 4.1.2 on 2023-03-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0009_remove_det_prestamo_libros_det_prestamo_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='nombre',
            new_name='nom_turno',
        ),
    ]
